# -*- coding: utf-8 -*-
"""python_basics_tanmayeemanasa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KIkQn9c6mrDGMFjtmMp7-6GAJis4eO7n
"""

# Task 1: Variables and Data Types
name = "Tanmayee Manasa"
age = 27
height = 5.7
is_student = True

print(name, age, height, is_student)

# Task 2: String Formatting
print(f"Name: {name} | Age: {age} | Height: {height} | Student: {is_student}")

# Task 3: Arithmetic Operations
age_in_months = age * 12
age_in_days = age * 365
remainder = age % 7
age_squared = age ** 2

print("Age in months:", age_in_months)
print("Age in days:", age_in_days)
print("Remainder when age is divided by 7:", remainder)
print("Age raised to the power of 2:", age_squared)

